# Generated by Django 5.1.1 on 2024-10-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='restaurantuser',
            options={'verbose_name': 'Restaurant User', 'verbose_name_plural': 'Restaurant Users'},
        ),
    ]
