# Generated by Django 5.1.1 on 2024-12-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menuitem_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='order',
        ),
    ]
